language: java
sudo: required

services:
  - docker

jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'

install: true

script:
  - mvn clean install -DskipDockerBuild -DskipTests=true -Dmaven.javadoc.skip=true -B -V